# ------------------------------------------------------------------------------------------------------------------------
# Action: Deploy Azure Resources via Bicep Files
# ------------------------------------------------------------------------------------------------------------------------
name: 2a - Deploy Infrastructure
run-name: 2a - Deploy Infrastructure to ENV ${{ inputs.deployEnvironment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod
          - lyle
          - scott
          - piotr
          - chris
          - nick
          - matt
      deploymentMode:
        description: 'Bicep Deploy Mode'
        required: true
        default: 'Incremental'
        type: choice
        options:
          - Incremental
          - Validation
          - Complete
      parameterFile:
        description: 'Parameter File'
        required: true
        default: 'main.gh.bicepparam'
      runBuildDeploy:
        description: 'Build and Deploy'
        required: false
        default: 'API+UI'
        type: choice
        options:
          - API
          - API+BATCH
          - API+UI
          - API+BATCH+UI
      createResourceGroup:
        description: Create Resource Group?
        type: boolean
        default: true
      publicAccessEnabled:
        description: Public Access Enabled?
        type: boolean
        default: true
      createDnsZones:
        description: Create DNS Zones?
        type: boolean
        default: true
      addRoleAssignments:
        description: Add Role Assignments?
        type: boolean
        default: true
      deployAIHub:
        description: Deploy AI Hub?
        type: boolean
        default: true
          
jobs:
  Deploy_Bicep:
    name: Deploy ${{ inputs.deployEnvironment }} Bicep
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      actions: read
      pages: write
    with:
      envCode: ${{ inputs.deployEnvironment }}
      templatePath: './infra/bicep/'
      templateFile: 'main.bicep'
      parameterFile: ${{ inputs.parameterFile }}
      parameterFileReplaceTokens: 'true'
      deploymentMode: ${{ inputs.deploymentMode }}
      createResourceGroup: ${{ inputs.createResourceGroup }}
      publicAccessEnabled: ${{ inputs.publicAccessEnabled }}
      createDnsZones: ${{ inputs.createDnsZones }}
      deployAIHub: ${{ inputs.deployAIHub }}
      deployBatchApp: ${{ contains('BATCH', inputs.runBuildDeploy) }}
      deployUIApp: ${{ contains('UI', inputs.runBuildDeploy) }}
      addRoleAssignments: ${{ inputs.addRoleAssignments }}
