# ------------------------------------------------------------------------------------------------------------------------
# Reusable Workflow: Deploying a Container App from a Registry
# See https://learn.microsoft.com/en-us/azure/ai-studio/how-to/create-projects?tabs=azurecli
# ------------------------------------------------------------------------------------------------------------------------
name: z_template_deploy_ai_hub_project
run-name: Deploy AI Hub Project
on:
  workflow_call:
    inputs:
      ENV_CODE:
        required: true
        type: string
      RESOURCE_GROUP:
        required: true
        type: string
      templatePath:
        required: false
        type: string
        default: 'infra/bicep/'
      templateFile:
        required: false
        type: string
        default: 'main.bicep'
      parameterFile:
        required: false
        type: string
        default: ''
      parameterFileReplaceTokens:
        required: false
        type: string
        default: 'false'
      PROJECT_NAME:
        required: true
        type: string

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  deploy:
    name: Deploy Project ${{ inputs.ENV_CODE }} ${{ inputs.PROJECT_NAME }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENV_CODE }}
    env:
      envCode: ${{ inputs.envCode }}
      generatedResourceGroupName: ${{ vars.RESOURCEGROUP_PREFIX }}-${{ inputs.envCode }}
    steps:
      - name: Get the current date
        id: get-date
        run: echo "DATE_TIME_STAMP=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: OIDC Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CICD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Find Azure Resources
        uses: azure/arm-deploy@v2
        id: run-bicep
        with:
          scope: resourcegroup
          region: ${{ vars.RESOURCEGROUP_LOCATION }}
          resourceGroupName: ${{ inputs.RESOURCE_GROUP }}
          deploymentName: ${{ inputs.templateFile }}-find-${{ steps.get-date.outputs.DATE_TIME_STAMP}}
          template: ${{ inputs.templatePath }}${{ inputs.templateFile }}
          parameters: ${{ inputs.templatePath }}${{ inputs.parameterFile }}
          deploymentMode: Incremental

      - name: Display Output
        run: |-
          echo "AI_HUB_ID=${{ steps.run-bicep.outputs.AI_HUB_ID }}"
          echo "AI_HUB_NAME=${{ steps.run-bicep.outputs.AI_HUB_NAME }}"

          echo "---------------------------------"
          echo "##[group]All Variables:"
          echo "Environment:"
          echo '${{ toJSON(env) }}'
          echo "Variables:"
          echo '${{ toJSON(vars) }}'
          echo "Secrets:"
          echo '${{ toJSON(secrets) }}'
          echo "Inputs:"
          echo '${{ toJSON(inputs) }}'
          echo "##[endgroup]"
        continue-on-error: true

      - name: OIDC Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CICD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy AI Foundry Project
        run: |
          az config set extension.dynamic_install_allow_preview=true          
          echo "az ml workspace create --kind project --resource-group ${{ inputs.RESOURCE_GROUP }} --hub-id ${{ inputs.HUB_ID }} --name ${{ inputs.PROJECT_NAME }}"
          az ml workspace create \
            --kind project \
            --resource-group ${{ inputs.RESOURCE_GROUP }} \
            --hub-id ${{ steps.run-bicep.outputs.AI_HUB_ID }} \
            --name ${{ inputs.PROJECT_NAME }}
