# ------------------------------------------------------------------------------------------------------------------------
# Reusable Workflow: Deploying a Container App from a Registry
# See https://learn.microsoft.com/en-us/azure/ai-studio/how-to/create-projects?tabs=azurecli
# ------------------------------------------------------------------------------------------------------------------------
name: z_template_deploy_ai_hub_project
run-name: Deploy AI Hub Project
on:
  workflow_call:
    inputs:
      ENV_CODE:
        required: true
        type: string
      RESOURCE_GROUP:
        required: true
        type: string
      # DEPLOY_OUTPUTS:
      #   required: true
      #   type: string
      HUB_ID:
        required: true
        type: string
      HUB_ID_1:
        required: true
        type: string
      HUB_ID_2:
        required: true
        type: string
      HUB_ID_3:
        required: true
        type: string
      HUB_NAME:
        required: true
        type: string
      HUB_NAME_1:
        required: true
        type: string
      HUB_NAME_2:
        required: true
        type: string
      HUB_NAME_3:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  deploy:
    name: deploy project ${{ inputs.ENV_CODE }} ${{ inputs.PROJECT_NAME }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENV_CODE }}
    steps:
      - name: Display Variables and Files
        run: |-
          echo "inputs.ENV_CODE=${{ inputs.ENV_CODE }}"
          echo "inputs.RESOURCE_GROUP=${{ inputs.RESOURCE_GROUP }}"
          echo "inputs.HUB_ID=${{ inputs.HUB_ID }}"
          echo "inputs.HUB_ID_1=${{ inputs.HUB_ID_1 }}"
          echo "inputs.HUB_ID_2=${{ inputs.HUB_ID_2 }}"
          echo "inputs.HUB_ID_3=${{ inputs.HUB_ID_3 }}"
          echo "inputs.HUB_NAME=${{ inputs.HUB_NAME }}"
          echo "inputs.HUB_NAME_1=${{ inputs.HUB_NAME_1 }}"
          echo "inputs.HUB_NAME_2=${{ inputs.HUB_NAME_2 }}"
          echo "inputs.HUB_NAME_3=${{ inputs.HUB_NAME_3 }}"
          echo "inputs.PROJECT_NAME=${{ inputs.PROJECT_NAME }}"

          echo "---------------------------------"
          echo "##[group]All Variables:"
          echo "Environment:"
          echo '${{ toJSON(env) }}'
          echo "Variables:"
          echo '${{ toJSON(vars) }}'
          echo "Secrets:"
          echo '${{ toJSON(secrets) }}'
          echo "Inputs:"
          echo '${{ toJSON(inputs) }}'
          echo "##[endgroup]"
        continue-on-error: true

      - name: OIDC Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CICD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy AI Foundry Project
        run: |
          az config set extension.dynamic_install_allow_preview=true          
          echo "az ml workspace create --kind project --resource-group ${{ inputs.RESOURCE_GROUP }} --hub-id ${{ inputs.HUB_ID }} --name ${{ inputs.PROJECT_NAME }}"
          az ml workspace create \
            --kind project \
            --resource-group ${{ inputs.RESOURCE_GROUP }} \
            --hub-id ${{ inputs.HUB_ID }} \
            --name ${{ inputs.PROJECT_NAME }}
